## Comando para resolver problema de fuentes en contenedor
## docker exec -u 0 api-service bash -c "apt-get update && apt-get install fontconfig ttf-dejavu -y"
version: "3.7"
services:

  db:
    container_name: 'postgres-database'
    image: postgres
    ##restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    ports:
      - 5432:5432

  adminer:
    container_name: 'php-my-admin'
    image: adminer
    ##restart: always
    ports:
      - 8080:8080

  api-service:
    container_name: 'api-service'
    depends_on:
      - db
    image: ${IMAGE_SAS_API}
    environment:
      TZ: ${TZ}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: ${DB_URL}
      REST_SERVER_PORT: ${REST_SERVER_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}
      JWT_SECRET_ID: ${JWT_SECRET_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      JPA_FORMAT_SQL: ${JPA_FORMAT_SQL}
      JPA_GENERATE_SCHEMA: ${JPA_GENERATE_SCHEMA}
      PATHS_ALLOWED: ${PATHS_ALLOWED}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      JPA_BATCH_SIZE: ${JPA_BATCH_SIZE}
      SECURITY_CIPHER_SECRET: ${SECURITY_CIPHER_SECRET}
    ports:
      - 8990:8990