spring:
  output:
    ansi:
      enabled: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_SHOW_SQL}
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: ${JPA_GENERATE_SCHEMA}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}
        order_inserts: true
        jdbc:
          batch_size: ${JPA_BATCH_SIZE}

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mail:
    host: "${EMAIL_HOST}"
    port: "${EMAIL_PORT}"
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: "${EMAIL_SMTP_AUTH}"
          starttls:
            enable: "${EMAIL_SMTP_STARTTLS}"
          ssl:
            trust: "${EMAIL_HOST}"
    debug: "${EMAIL_DEBUG_ENABLED}"
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
server:
  port: ${REST_NATIVE_SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

logging:
  level:
    org:
      springframework:
        web: error
      hibernate: error
    com:
      mexico:
        sas:
          nativequeries:
            api: ${LOGGER_LEVEL}

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %logger.%M - %msg%n"
    file: "%d{HH:mm:ss} %logger.%M - %msg%n"
  file:
    name: /tmp/sas-native/logs/api-service.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: shutdown
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true